"""add organization ownership

Revision ID: da56018aa9f0
Revises: d3d15b32e51c
Create Date: 2026-05-06 11:47:39.575327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da56018aa9f0'
down_revision: Union[str, Sequence[str], None] = 'd3d15b32e51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.add_column('booking', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'booking', 'property', ['property_id'], ['id'])
    op.add_column('ingestionjob', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ingestionjob_organization_id'), 'ingestionjob', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'ingestionjob', 'organizations', ['organization_id'], ['id'])
    op.add_column('property', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('property', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('property', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_property_city'), 'property', ['city'], unique=False)
    op.create_index(op.f('ix_property_organization_id'), 'property', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'property', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_index(op.f('ix_property_organization_id'), table_name='property')
    op.drop_index(op.f('ix_property_city'), table_name='property')
    op.drop_column('property', 'updated_at')
    op.drop_column('property', 'created_at')
    op.drop_column('property', 'organization_id')
    op.drop_constraint(None, 'ingestionjob', type_='foreignkey')
    op.drop_index(op.f('ix_ingestionjob_organization_id'), table_name='ingestionjob')
    op.drop_column('ingestionjob', 'organization_id')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'created_at')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
