"""add ingestion error reporting

Revision ID: 47d1ed690689
Revises: da56018aa9f0
Create Date: 2026-05-06 12:23:02.028910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47d1ed690689'
down_revision: Union[str, Sequence[str], None] = 'da56018aa9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestionjob.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_errors_job_id'), 'ingestion_errors', ['job_id'], unique=False)
    op.create_index(op.f('ix_ingestion_errors_organization_id'), 'ingestion_errors', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_errors_organization_id'), table_name='ingestion_errors')
    op.drop_index(op.f('ix_ingestion_errors_job_id'), table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    # ### end Alembic commands ###
